apiVersion: v1
kind: Service
metadata:
  name: datacollect-svc
  labels:
    run: datacollect-svc
spec:
  type: NodePort
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: datacollect 